### ISSUE TITLE
Do both powa-collector and powa-web need to expose 8888 port?

### ISSUE THREAD

**Issue by tarkhil** [powa-team/powa-podman#15]
Hello

I'm a bit confused that powa-collector and powa-web both exposes port 8888. 

Do they interact? Or do I need only one of them in remote setup?

**Comment by rjuju** [comment]
Oops, powa-collector should expose port 8888, as it won't listen on it (which is indirectly hinted by the compose image that doesn't do anythint with this port for powa-collector).  I will fix that, unless you want to submit a PR.

**Comment by tarkhil** [comment]
Fix it please, it would be faster than making a PR)

**Comment by rjuju** [comment]
Sure, this is fixed as of https://github.com/powa-team/powa-podman/commit/8a6cd051ac20c4d3c3434424da3556423e5529a9.
