### ISSUE TITLE
Operational instructions missing

### ISSUE THREAD

**Issue by stitch** [powa-team/powa-podman#3]
Operation instructions to get the images running and interacting with each other is missing. I've written a bunch of them while setting up this environment. Without instructions such as these, it requires an hour of rtfm or a skilled docker user to get things done.

Here are the things i wrote down, which can largely be added to the readme.md file for best discovery.

My usecase: i wanted a quick and easy impression if there are index optimizations on a database i inherited without becoming a postgres administrator, and while running on macos. After a few attempts with building VMs and erroneous installation of postgresql and powa, i decided to give up and found this docker solution which saves major headaches!

Running the images
--------------------
Make sure you have docker installed and running. Note that when you stop the container, your data is lost. Retaining data is beyond the scope of this walkthrough.

### 1: Archivist image (database + extensions)

In a directory with a Dockerfile, for example in powa-archivist/12:
```
docker build .
```

after building you'll find a nameless image in your image list:

```
docker images
```

To give these images a name:
```
docker image tag 84e03a48510f powa-dev-web
```

You can run this with:
```
docker run powa-dev-web
```

This will give you the following warning:
```
Error: Database is uninitialized and superuser password is not specified.
       You must specify POSTGRES_PASSWORD to a non-empty value for the
       superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".

       You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
       connections without a password. This is *not* recommended.

       See PostgreSQL documentation about "trust":
       https://www.postgresql.org/docs/current/auth-trust.html
```

Using the -e parameter, you can pass environment variables how to run the image.

To run the database without any form of security you can for example run:
```
docker run -e POSTGRES_HOST_AUTH_METHOD=trust powa-dev-web
```

Lastly you need to expose the database to your computer using port mapping:
```
docker run -e POSTGRES_HOST_AUTH_METHOD=trust -p5432:5432 --hostname powa-repository --name powa-repository powa-dev-web
```

Now you can log into the database and perform arbitrary commands like this:
```
docker exec -it powa-repository bash
```

From there you can do the other "classic" administration stuff for postgress, like creating a user and a database in an insecure manner:
```
su postgres
createuser root
psql
ALTER USER root WITH PASSWORD 'root';
CREATE DATABASE root;
```

Make sure to first run the archivist container, and then start the web container. The web container needs to be started with port forwarded parameters:

### 2: Web tool

Create a docker build in the web directory, and also run this container, in this case an image without a name:
```
docker run -p8888:8888 44200549b847
```

### 3: Setting up a  network

Then the web interface is visible. But you cannot login yet, as you'll run into this error:
```
    (Background on this error at: http://sqlalche.me/e/e3q8)
[W 200616 09:03:57 web:2162] 403 POST /login/?next=%2F (172.17.0.1) 8.63ms
[E 200616 09:03:57 user:20] (psycopg2.OperationalError) could not translate host name "powa-repository" to address: Name or service not known
```

This is because the containers cannot see each other. So you'll have to make a network, like this;
```
docker network create powanet
docker network connect powanet powa-repository
docker network connect powanet heuristic_pasteur
```

Now you can login on the web interface _without credentials_! This will be a login as postgres which can do anything and everything.

### 4: Getting optimization suggestions

Since the database is exposed to your local system on port 5432, you can run queries and software that uses this database. With this you can use the POWA tools such as database optimization.

You'll notice no optimization suggestions. That is because the extensions have to be enabled per database. So run the following on the database that you are using:
```
\c root
CREATE EXTENSION pg_stat_statements;
CREATE EXTENSION btree_gist;
CREATE EXTENSION powa;
CREATE EXTENSION pg_qualstats;
CREATE EXTENSION pg_stat_kcache;
```

Now you can run queries like pg_qualstats from psql or the web interface:
```
select * from pg_qualstats;
```

**Comment by rjuju** [comment]
Hello,

I'm glad that those images could be helpful, and I'm sorry that the documentation is quite poor.  I also don't know much about docker, and those images might not be the state of the art.

Thanks a lot for this extensive guide!

Have you considered using the docker-compose files (https://github.com/powa-team/powa-docker/tree/master/compose)?  Those should help to setup everything automatically, including downloading the images from docker-hub repository.

**Comment by stitch** [comment]
Yes. I tried docker compose up or something like that. Wrong filenames. Thus having to rename a file felt like it was not intended to be used as is. Fearing even more debugging i dropped it and continue figuring out the way to do things manually. (I suppose docker compose also creates a network between the components, which would be nice.)

The easiest fix for docker compose would be to have the files named the way docker compose would expect them, and because you'll then get same filenames twice, add them in separate directories describing what they do. ((Or have a readme in the directory stating that the files are intended to be renamed. ... but then -> which file did you rename and what does it do? :)  ))

**Comment by rjuju** [comment]
I just tried on a macos machine and I didn't notice any specific issue:

```
$ docker ps -a |grep -c powateam
0

$ docker-compose -f powa_standalone_mode.yml up > log 2>&1
[...]
```

another terminal:
```
$ tail -f log
powa-standalone-repository | 2020-06-17 06:02:34.264 UTC [83] LOG:  database system was shut down at 2020-06-17 06:02:34 UTC
powa-standalone-repository | 2020-06-17 06:02:34.271 UTC [1] LOG:  database system is ready to accept connections
powa-standalone-repository | 2020-06-17 06:02:34.272 UTC [89] LOG:  pg_wait_sampling collector started
powa-standalone-repository | 2020-06-17 06:02:34.275 UTC [90] LOG:  POWA connected to database powa

$ docker ps -a |grep powateam
1f81da8dc753        powateam/powa-web            "powa-web"               2 minutes ago       Up 2 minutes               0.0.0.0:8888->8888/tcp      powa-standalone-web
add998f7299d        powateam/powa-archivist-12   "docker-entrypoint.s…"   2 minutes ago       Up 2 minutes               5432/tcp                    powa-standalone-repository

$ wget 0.0.0.0:8888
--2020-06-17 08:06:10--  http://0.0.0.0:8888/
Connecting to 0.0.0.0:8888... connected.
HTTP request sent, awaiting response... 302 Found
Location: /login/?next=%2F [following]
--2020-06-17 08:06:10--  http://0.0.0.0:8888/login/?next=%2F
Reusing existing connection to 0.0.0.0:8888.
HTTP request sent, awaiting response... 403 OK
2020-06-17 08:06:10 ERROR 403: OK.
```

Do you mean that the compose files aren't named with the default name?  Since I provide both "standalone" and "remote mode" compose files, it just seemed easier to name them accordingly and let users specify the "-f" argument depending on their needs rather than relying on being in a specific directory, as you're in any case more likely to call docker-compose from any directory using absolute file path when you need to bring the environment up.

I can add some more documentation on how those files are supposed to be used, if that's how docker-compose is supposed to be used of course.

**Comment by stitch** [comment]
I think adding some documentations would help a lot!

Especially first timers, as they would be able to the fastest results with the least amount of effort by just copy-pasting your docker compose command.

Wish i would have known :) But now i know more about docker ;)

**Comment by stitch** [comment]
I think the powa_standalone_mode needs a port mapping out of the container. What is the use of running this if you can't get data to analyze into the database :)

**Comment by rjuju** [comment]
Well, I did expose the postgres port in some previous other compose file, and got quite some criticism, saying that people using docker will have their app in docker anyway so they don't need an exposed port, or if they need to they can just copy/paste the file and expose it to the value they want.

So I think the best thing to do would be to add some quickstarter guide on how to use the file (the `-f` option and maybe other), and advising to use the file as a template to modify according to one needs, maybe with some example (how to expose a port or things like that).

**Comment by rjuju** [comment]
I just pushed https://github.com/powa-team/powa-docker/commit/5150551a3118a9b0754689dcc8102a9ac99fa6bf that should help people getting started with the docker-compose images.
